
package pl.ene.weather.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.8
 * 2016-05-03T23:03:28.841+02:00
 * Generated source version: 2.7.8
 */

@WebFault(name = "GetWeatherError", targetNamespace = "http://ene.pl/weather/service/types")
public class GetWeatherError extends Exception {
    
    private pl.ene.weather.service.types.GetWeatherError getWeatherError;

    public GetWeatherError() {
        super();
    }
    
    public GetWeatherError(String message) {
        super(message);
    }
    
    public GetWeatherError(String message, Throwable cause) {
        super(message, cause);
    }

    public GetWeatherError(String message, pl.ene.weather.service.types.GetWeatherError getWeatherError) {
        super(message);
        this.getWeatherError = getWeatherError;
    }

    public GetWeatherError(String message, pl.ene.weather.service.types.GetWeatherError getWeatherError, Throwable cause) {
        super(message, cause);
        this.getWeatherError = getWeatherError;
    }

    public pl.ene.weather.service.types.GetWeatherError getFaultInfo() {
        return this.getWeatherError;
    }
}
