package pl.ene.weather.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2016-05-03T23:03:28.858+02:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://ene.pl/weather/service", name = "WeatherPortTypeSOAP")
@XmlSeeAlso({pl.ene.weather.service.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WeatherPortTypeSOAP {

    @WebMethod(action = "/getWeather")
    @WebResult(name = "GetWeatherOutput", targetNamespace = "", partName = "GetWeatherOutput")
    public pl.ene.weather.service.types.GetWeatherOutput getWeather(
        @WebParam(partName = "GetWeatherInput", name = "GetWeatherInput", targetNamespace = "")
        pl.ene.weather.service.types.GetWeatherInput getWeatherInput
    ) throws GetWeatherError;
}
