package pl.ene.weather.service;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2016-05-03T23:03:28.868+02:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "WeatherService", 
                  wsdlLocation = "classpath:wsdl/WeatherService.wsdl",
                  targetNamespace = "http://ene.pl/weather/service") 
public class WeatherService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ene.pl/weather/service", "WeatherService");
    public final static QName SamplePortSOAP = new QName("http://ene.pl/weather/service", "SamplePortSOAP");
    static {
        URL url = WeatherService.class.getClassLoader().getResource("wsdl/WeatherService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(WeatherService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/WeatherService.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public WeatherService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WeatherService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WeatherService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WeatherService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WeatherService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WeatherPortTypeSOAP
     */
    @WebEndpoint(name = "SamplePortSOAP")
    public WeatherPortTypeSOAP getSamplePortSOAP() {
        return super.getPort(SamplePortSOAP, WeatherPortTypeSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherPortTypeSOAP
     */
    @WebEndpoint(name = "SamplePortSOAP")
    public WeatherPortTypeSOAP getSamplePortSOAP(WebServiceFeature... features) {
        return super.getPort(SamplePortSOAP, WeatherPortTypeSOAP.class, features);
    }

}
